return {
    {
        caption = '道具(&I)',
        key = 'item_list',
        enabled = false,
        [1] = {
            caption = '茶水类(&D)',
            key = 'drinks',
            format = 'x{}',
            [1] = { caption = '绿茶', key = 'green_tea', type = 'prompt' },
            [2] = { caption = '咖啡', key = 'coffee', type = 'prompt' },
            [3] = { caption = '红茶', key = 'black_tea', type = 'prompt' },
            [4] = { caption = '安眠茶', key = 'sleep_tea', type = 'prompt' },
            [5] = { caption = '壮阳茶', key = 'stimulant', type = 'prompt' },
            [6] = { caption = '媚药', key = 'love_potion', type = 'prompt' },
            [7] = { caption = '避孕药', key = 'after_pill', type = 'prompt' },
        },
        [2] = {
            caption = '礼物类(&P)',
            key = 'presents',
            format = 'x{}',
            [1] = { caption = '零食', key = 'sweets', type = 'prompt' },
            [2] = { caption = '礼物', key = 'present', type = 'prompt' },
        },
        [3] = {
            caption = '书籍类(&B)',
            key = 'books',
            format = 'x{}',
            [1] = { caption = '冒险的书', key = 'adventure_book', type = 'prompt' },
            [2] = { caption = '色色的书', key = 'naughty_book', type = 'prompt' },
            [3] = { caption = '小薄本', key = 'doujinshi', type = 'prompt' },
        },
        [4] = {
            caption = '家具类(&H)',
            key = 'household_items',
            [1] = { caption = '安眠枕', key = 'soft_pillow', type = 'check' },
            [2] = { caption = '羽毛被', key = 'feather_mattress', type = 'check' },
            [3] = { caption = '哑铃', key = 'dumbbell', type = 'check' },
            [4] = { caption = '铁木屐', key = 'iron_sandals', type = 'check' },
        },
        [5] = {
            caption = 'H类(&S)',
            key = 'sex_items',
            [1] = { caption = '安全套', key = 'condom', type = 'prompt', format = 'x{}' },
            [2] = { caption = '跳蛋', key = 'vibrator', type = 'check' },
            [3] = { caption = '按摩棒', key = 'dildo', type = 'check' },
            [4] = { caption = '菊穴按摩棒', key = 'anal_dildo', type = 'check' },
        },
    },
    {
        caption = '状态(&S)',
        key = 'status',
        enabled = false,
        [1] = {
            caption = '时间(&T)',
            key = 'time',
            [1] = { caption = '日', key = 'day', type = 'prompt' },
            [2] = { caption = '时', key = 'hour', type = 'prompt' },
            [3] = { caption = '分', key = 'minute', type = 'prompt' },
            [4] = { caption = '周', key = 'week', type = 'prompt' },
        },
    },
    {
        caption = '帮助(&H)',
        key = 'help',
        enabled = true,
        [1] = { caption = '文档(&D)', key = 'documentation', type = 'action' },
        [2] = { caption = '关于(&A)', key = 'about', type = 'action' },
    },
}
